config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_brewfile:
    src: Brewfile
    dst: ~/Brewfile
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
profiles:
  elementary:
    dotfiles:
    - f_zshrc
    - f_zshenv
  mac:
    dotfiles:
    - f_zshrc
    - f_brewfile
    - f_zprofile
