config:
  backup: true
  create: true
  dotpath: dotfiles
  cmpignore:
  - '*.log'
  upignore:
  - '*.log'
  instignore:
  - '*.log'
  impignore:
  - '*.log'

dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_brewfile:
    src: Brewfile
    dst: ~/Brewfile
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  d_btop:
    src: config/btop
    dst: ~/.config/btop/
    cmpignore:
    - '*/themes'
    upignore:
    - '*/themes'
    instignore:
    - '*/themes'
  d_foot:
    src: config/foot
    dst: ~/.config/foot/
  d_mako:
    src: config/mako
    dst: ~/.config/mako
  d_micro:
    src: config/micro
    dst: ~/.config/micro/
    cmpignore:
    - '*/backups'
    - '*/buffers'
    upignore:
    - '*/backups'
    - '*/buffers'
    instignore:
    - '*/backups'
    - '*/buffers'
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch/
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger/
    chmod: '755'
  d_sway:
    src: config/sway
    dst: ~/.config/sway/
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar/
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi/
  f_zsh_aliases:
    src: zsh_aliases
    dst: ~/.zsh_aliases
  d_nvim_plugins:
    src: config/nvim/lua/custom/plugins
    dst: ~/.config/nvim/lua/custom/plugins
  d_nvim_after:
    src: config/nvim/after
    dst: ~/.config/nvim/after
profiles:
  fedora:
    dotfiles:
    - d_nvim_plugins
    - d_nvim_after
    - f_zshrc
    - f_p10k.zsh
    - d_btop
    - d_foot
    - d_mako
    - d_micro
    - d_neofetch
    - d_ranger
    - d_sway
    - d_waybar
    - d_wofi
    - f_zsh_aliases
  mac:
    dotfiles:
    - d_nvim_plugins
    - d_nvim_after
    - f_zshrc
    - f_brewfile
    - f_zprofile
    - f_zsh_aliases
