config:
  backup: true
  create: true
  dotpath: dotfiles
  cmpignore:
  - '*.log'
  upignore:
  - '*.log'
  instignore:
  - '*.log'
  impignore:
  - '*.log'

dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_brewfile:
    src: Brewfile
    dst: ~/Brewfile
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  d_btop:
    src: config/btop
    dst: ~/.config/btop/
    cmpignore:
    - '*/themes'
    upignore:
    - '*/themes'
    instignore:
    - '*/themes'
  d_foot:
    src: config/foot
    dst: ~/.config/foot/
  d_mako:
    src: config/mako
    dst: ~/.config/mako
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch/
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger/
    chmod: '755'
  d_sway:
    src: config/sway
    dst: ~/.config/sway/
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar/
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi/
  f_zsh_aliases:
    src: zsh_aliases
    dst: ~/.zsh_aliases
  d_nvim_plugins:
    src: config/nvim/lua/custom/plugins
    dst: ~/.config/nvim/lua/custom/plugins
  d_nvim_after:
    src: config/nvim/after
    dst: ~/.config/nvim/after
  f_com.googlecode.iterm2.plist:
    src: com.googlecode.iterm2.plist
    dst: ~/com.googlecode.iterm2.plist
  f_ignore:
    src: ignore
    dst: ~/.ignore
  f_warm-tones-wallpaper.jpg:
    src: Imagens/warm-tones-wallpaper.jpg
    dst: ~/Imagens/warm-tones-wallpaper.jpg
    chmod: '777'
  f_default.profile:
    src: config/sublime-text/Packages/sublime-profiles/Data/Default.profile
    dst: ~/.config/sublime-text/Packages/sublime-profiles/Data/Default.profile
  f_writer.profile:
    src: config/sublime-text/Packages/sublime-profiles/Data/Writer.profile
    dst: ~/.config/sublime-text/Packages/sublime-profiles/Data/Writer.profile
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
  d_yt-dlp:
    src: config/yt-dlp
    dst: ~/.config/yt-dlp
  f_tokyonight_night.tmtheme:
    src: Library/Application Support/Sublime Text 3/Packages/tokyonight_night.tmTheme
    dst: ~/Library/Application Support/Sublime Text 3/Packages/tokyonight_night.tmTheme
  f_data_default.profile:
    src: Library/Application Support/Sublime Text 3/Packages/sublime-profiles/Data/Default.profile
    dst: ~/Library/Application Support/Sublime Text 3/Packages/sublime-profiles/Data/Default.profile
  f_data_writer.profile:
    src: Library/Application Support/Sublime Text 3/Packages/sublime-profiles/Data/Writer.profile
    dst: ~/Library/Application Support/Sublime Text 3/Packages/sublime-profiles/Data/Writer.profile
  f_nvim_lazy-lock.json:
    src: config/nvim/lazy-lock.json
    dst: ~/.config/nvim/lazy-lock.json
profiles:
  base:
    dotfiles:
      - f_nvim_lazy-lock.json
      - d_nvim_plugins
      - d_nvim_after
      - f_zshrc
      - f_zsh_aliases
      - f_p10k.zsh
      - d_btop
      - f_ignore
  fedora:
    dotfiles:
      - d_foot
      - d_mako
      - d_neofetch
      - d_ranger
      - d_sway
      - d_waybar
      - d_wofi
      - f_warm-tones-wallpaper.jpg
      - d_mpv
      - d_yt-dlp
      - f_default.profile
      - f_writer.profile
    include:
      - base
  mac:
    dotfiles:
      - f_brewfile
      - f_zprofile
      - f_com.googlecode.iterm2.plist
      - f_tokyonight_night.tmtheme
      - f_data_default.profile
      - f_data_writer.profile
    include:
      - base
